spring:
  datasource:
    password: 12341234
    url: jdbc:mysql://localhost:3306/timelydb
    username: root

    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

